import immunityImg from '@/assets/remedies/immunity.jpg';
import digestionImg from '@/assets/remedies/digestion.jpg';
import skinImg from '@/assets/remedies/skin.jpg';
import hairImg from '@/assets/remedies/hair.jpg';
import painImg from '@/assets/remedies/pain.jpg';
import stressImg from '@/assets/remedies/stress.jpg';

import drRajesh from '@/assets/specialists/dr-rajesh.jpg';
import drPriya from '@/assets/specialists/dr-priya.jpg';
import drAnita from '@/assets/specialists/dr-anita.jpg';
import drVikram from '@/assets/specialists/dr-vikram.jpg';
import drSanjay from '@/assets/specialists/dr-sanjay.jpg';
import drKavita from '@/assets/specialists/dr-kavita.jpg';

import { Shield, Heart, Sparkles, Flame, Eye, Brain, Leaf } from 'lucide-react';

export interface Specialist {
  name: string;
  title: string;
  image: string;
}

export interface Remedy {
  id: string;
  category: string;
  image: string;
  title: string;
  subtitle: string;
  description: string;
  ingredients: { name: string; quantity: string; purpose: string }[];
  benefits: string[];
  steps: string[];
  precautions: string[];
  bestTimeToUse: string;
  doshaAffinity: string[];
  difficulty: string;
  duration: string;
  specialist: Specialist;
  tags: string[];
}

export const remedyCategories = [
  { id: 'all', label: 'All Remedies', icon: Leaf },
  { id: 'immunity', label: 'Immunity', icon: Shield },
  { id: 'digestion', label: 'Digestion', icon: Heart },
  { id: 'skin', label: 'Skin Care', icon: Sparkles },
  { id: 'hair', label: 'Hair Care', icon: Flame },
  { id: 'pain', label: 'Pain Relief', icon: Eye },
  { id: 'stress', label: 'Stress & Sleep', icon: Brain },
];

export const remedies: Remedy[] = [
  {
    id: '1',
    category: 'immunity',
    image: immunityImg,
    title: 'Golden Turmeric Milk (Haldi Doodh)',
    subtitle: 'Ancient immunity-boosting elixir',
    description: 'A powerful Ayurvedic drink to boost immunity, fight inflammation, and promote healing. Known as "liquid gold" in Ayurveda, this remedy has been used for over 4,000 years to strengthen the body\'s natural defenses. Best consumed warm before bedtime for optimal absorption.',
    ingredients: [
      { name: 'Turmeric powder', quantity: '½ tsp', purpose: 'Anti-inflammatory, curcumin-rich' },
      { name: 'Black pepper', quantity: '1 pinch', purpose: 'Enhances curcumin absorption by 2000%' },
      { name: 'Warm milk', quantity: '1 cup', purpose: 'Carrier for fat-soluble curcumin' },
      { name: 'Raw honey', quantity: '1 tsp', purpose: 'Antibacterial, natural sweetener' },
      { name: 'Ghee', quantity: '½ tsp', purpose: 'Aids bioavailability of turmeric' },
    ],
    benefits: ['Boosts immunity & white blood cell count', 'Powerful anti-inflammatory properties', 'Improves sleep quality & duration', 'Fights bacterial & viral infections', 'Supports liver detoxification', 'Promotes healthy skin from within'],
    steps: [
      'Pour 1 cup of whole milk (or plant-based alternative) into a small saucepan.',
      'Add ½ tsp of organic turmeric powder and a generous pinch of freshly ground black pepper.',
      'Add ½ tsp of pure ghee (clarified butter) to the mixture.',
      'Heat on medium-low flame, stirring continuously for 5 minutes. Do not let it boil.',
      'Once warm and fragrant, pour into a cup and let it cool slightly for 2 minutes.',
      'Add 1 tsp of raw honey (never add honey to boiling liquid as it loses its properties).',
      'Stir well and drink warm, 30 minutes before bedtime.',
    ],
    precautions: [
      'Avoid if you have gallbladder issues or bile duct obstruction.',
      'Do not consume on an empty stomach if you have acid reflux.',
      'Pregnant women should consult their doctor before regular use.',
      'May interact with blood-thinning medications.',
      'Use organic turmeric to avoid pesticide residues.',
    ],
    bestTimeToUse: 'Before bedtime, 30 minutes after dinner',
    doshaAffinity: ['Vata', 'Kapha'],
    difficulty: 'Easy',
    duration: '10 mins',
    specialist: { name: 'Dr. Rajesh Sharma', title: 'Senior Ayurvedic Physician', image: drRajesh },
    tags: ['immunity', 'anti-inflammatory', 'sleep', 'detox'],
  },
  {
    id: '2',
    category: 'immunity',
    image: immunityImg,
    title: 'Tulsi Kadha (Immunity Tea)',
    subtitle: 'Sacred herbal immunity decoction',
    description: 'Traditional herbal decoction with holy basil, ginger, and spices that strengthens the immune system and fights respiratory issues. Tulsi (Holy Basil) is revered as "The Queen of Herbs" in Ayurveda for its powerful adaptogenic and immunomodulatory properties.',
    ingredients: [
      { name: 'Fresh Tulsi leaves', quantity: '10-12 leaves', purpose: 'Adaptogenic, antimicrobial' },
      { name: 'Fresh ginger', quantity: '1 inch piece', purpose: 'Anti-inflammatory, digestive aid' },
      { name: 'Black pepper', quantity: '4-5 whole', purpose: 'Expectorant, bioenhancer' },
      { name: 'Cinnamon stick', quantity: '1 small', purpose: 'Antiviral, blood sugar regulation' },
      { name: 'Jaggery', quantity: '1 tsp', purpose: 'Natural sweetener, iron-rich' },
    ],
    benefits: ['Fights cold, cough & respiratory infections', 'Detoxifies the body naturally', 'Boosts respiratory health', 'Rich in antioxidants & vitamin C', 'Reduces stress hormones', 'Supports cardiovascular health'],
    steps: [
      'Crush the tulsi leaves gently with a mortar and pestle to release essential oils.',
      'Grate the ginger finely and lightly crush the black peppercorns.',
      'Bring 2 cups of water to a boil in a stainless steel or clay pot.',
      'Add all crushed ingredients and the cinnamon stick to the boiling water.',
      'Reduce flame to low and simmer for 10-12 minutes until water reduces to 1 cup.',
      'Strain through a fine mesh into a cup.',
      'Add jaggery while still warm and stir until dissolved.',
      'Sip slowly while hot for maximum benefit.',
    ],
    precautions: [
      'Avoid during pregnancy in large quantities as tulsi may stimulate uterine contractions.',
      'May lower blood sugar — diabetics on medication should monitor levels.',
      'Do not consume more than 2 cups daily.',
      'Avoid if you are scheduled for surgery (blood-thinning effects).',
    ],
    bestTimeToUse: 'Morning on empty stomach or evening',
    doshaAffinity: ['Kapha', 'Vata'],
    difficulty: 'Easy',
    duration: '15 mins',
    specialist: { name: 'Dr. Priya Patel', title: 'Ayurvedic Herbalist', image: drPriya },
    tags: ['immunity', 'respiratory', 'detox', 'antioxidant'],
  },
  {
    id: '3',
    category: 'digestion',
    image: digestionImg,
    title: 'Jeera Water for Digestion',
    subtitle: 'Simple yet powerful digestive tonic',
    description: 'A simple yet effective Ayurvedic remedy using cumin seeds to improve digestion, reduce bloating, and enhance metabolism. Cumin (Jeera) is considered one of the most important spices in Ayurveda for its ability to kindle the digestive fire (Agni).',
    ingredients: [
      { name: 'Cumin seeds', quantity: '1 tbsp', purpose: 'Stimulates digestive enzymes' },
      { name: 'Water', quantity: '2 cups', purpose: 'Base medium' },
      { name: 'Lemon juice', quantity: '½ lemon', purpose: 'Alkalizing, vitamin C' },
      { name: 'Rock salt', quantity: '1 pinch', purpose: 'Mineral-rich, aids absorption' },
    ],
    benefits: ['Stimulates digestive enzyme production', 'Reduces bloating & gas instantly', 'Boosts metabolic rate by 15-20%', 'Gentle detoxification of digestive tract', 'Improves nutrient absorption', 'Regulates bowel movements'],
    steps: [
      'Measure 1 tablespoon of whole cumin seeds (avoid pre-ground for best potency).',
      'Soak the cumin seeds in 2 cups of room temperature water overnight (8-10 hours).',
      'In the morning, transfer the soaked seeds and water to a saucepan.',
      'Bring to a gentle boil, then simmer on low flame for 5 minutes.',
      'Strain into a glass, pressing the seeds to extract maximum flavor.',
      'Add juice of half a lemon and a pinch of rock salt.',
      'Drink warm on an empty stomach, 30 minutes before breakfast.',
    ],
    precautions: [
      'May cause heartburn if consumed in excess.',
      'Not recommended for people with chronic acid reflux (GERD).',
      'Reduce quantity during menstruation as it may increase flow.',
      'Start with ½ tablespoon if you are new to this remedy.',
    ],
    bestTimeToUse: 'Early morning, on empty stomach',
    doshaAffinity: ['Pitta', 'Kapha'],
    difficulty: 'Easy',
    duration: '10 mins + overnight soak',
    specialist: { name: 'Dr. Anita Desai', title: 'Digestive Health Specialist', image: drAnita },
    tags: ['digestion', 'metabolism', 'bloating', 'detox'],
  },
  {
    id: '4',
    category: 'digestion',
    image: digestionImg,
    title: 'Triphala Churna Remedy',
    subtitle: 'The legendary Ayurvedic trio',
    description: 'The legendary Ayurvedic trio of Amla, Haritaki, and Bibhitaki for complete digestive wellness and gentle detoxification. Triphala literally means "three fruits" and is considered the most versatile and commonly used herbal formulation in Ayurveda.',
    ingredients: [
      { name: 'Triphala powder', quantity: '1 tsp', purpose: 'Tri-doshic balancer, colon cleanser' },
      { name: 'Warm water', quantity: '1 cup', purpose: 'Aids dissolution and absorption' },
      { name: 'Honey', quantity: '½ tsp (optional)', purpose: 'Carrier, antibacterial' },
    ],
    benefits: ['Gentle yet effective colon cleansing', 'Regulates bowel movements naturally', 'Improves nutrient absorption by 30%', 'One of the richest sources of antioxidants', 'Strengthens eye health', 'Supports healthy weight management'],
    steps: [
      'Boil 1 cup of filtered water and let it cool to lukewarm temperature.',
      'Add 1 teaspoon of high-quality Triphala churna (powder) to the water.',
      'Stir vigorously for 30 seconds to dissolve the powder completely.',
      'Let it steep for 2 minutes to allow the herbs to infuse.',
      'Optionally add ½ teaspoon of raw honey for taste (skip if diabetic).',
      'Drink the entire mixture at once, including any sediment at the bottom.',
    ],
    precautions: [
      'Do not use during pregnancy or breastfeeding.',
      'May cause loose stools initially — reduce dosage if this occurs.',
      'Avoid if you have diarrhea or dysentery.',
      'Take a break of 2 weeks after every 2 months of continuous use.',
      'Not suitable for children under 12 years.',
    ],
    bestTimeToUse: 'Before bedtime or early morning',
    doshaAffinity: ['Vata', 'Pitta', 'Kapha'],
    difficulty: 'Easy',
    duration: '5 mins',
    specialist: { name: 'Dr. Vikram Chauhan', title: 'Panchakarma Expert', image: drVikram },
    tags: ['digestion', 'detox', 'weight', 'antioxidant'],
  },
  {
    id: '5',
    category: 'skin',
    image: skinImg,
    title: 'Turmeric & Honey Face Pack',
    subtitle: 'Ancient beauty ritual for glowing skin',
    description: 'An ancient Ayurvedic beauty remedy that brightens skin, fights acne, and provides a natural glow using simple kitchen ingredients. This face pack has been the secret behind the radiant skin of Indian women for centuries.',
    ingredients: [
      { name: 'Turmeric powder', quantity: '½ tsp', purpose: 'Brightening, antiseptic' },
      { name: 'Raw honey', quantity: '1 tbsp', purpose: 'Humectant, antibacterial' },
      { name: 'Fresh yogurt', quantity: '1 tbsp', purpose: 'Lactic acid exfoliant, probiotic' },
      { name: 'Rose water', quantity: '1 tsp', purpose: 'Toner, pH balancer' },
    ],
    benefits: ['Brightens complexion visibly in 2 weeks', 'Fights acne-causing bacteria', 'Reduces hyperpigmentation & dark spots', 'Natural deep moisturization', 'Evens out skin tone', 'Delays signs of aging'],
    steps: [
      'Cleanse your face thoroughly with lukewarm water and pat dry.',
      'In a clean bowl, mix ½ tsp turmeric powder with 1 tbsp raw honey.',
      'Add 1 tbsp fresh yogurt (not flavored) and mix into a smooth paste.',
      'Apply evenly on face and neck using clean fingertips, avoiding eye area.',
      'Leave the pack on for 15-20 minutes. You may feel a slight tingling — this is normal.',
      'Rinse off with lukewarm water using gentle circular motions.',
      'Splash cold water to close pores, then spritz rose water as a toner.',
      'Follow with your regular moisturizer.',
    ],
    precautions: [
      'Do a patch test on your inner wrist 24 hours before first use.',
      'Turmeric may temporarily stain fair skin — use sparingly.',
      'Avoid if you have open wounds, cuts, or severe acne inflammation.',
      'Do not use more than 2-3 times per week.',
      'Use kasturi turmeric (wild turmeric) for face to avoid staining.',
    ],
    bestTimeToUse: 'Evening, 2-3 times per week',
    doshaAffinity: ['Pitta', 'Kapha'],
    difficulty: 'Easy',
    duration: '25 mins',
    specialist: { name: 'Dr. Kavita Rao', title: 'Ayurvedic Dermatologist', image: drKavita },
    tags: ['skincare', 'brightening', 'acne', 'anti-aging'],
  },
  {
    id: '6',
    category: 'skin',
    image: skinImg,
    title: 'Aloe Vera Skin Soothing Gel',
    subtitle: 'Nature\'s miracle healer',
    description: 'Fresh aloe vera application for healing sunburns, reducing inflammation, and keeping skin hydrated and youthful. Aloe Vera, known as "Kumari" in Ayurveda, is celebrated for its cooling, soothing, and regenerative properties.',
    ingredients: [
      { name: 'Fresh aloe vera gel', quantity: '2 tbsp', purpose: 'Cooling, healing, hydrating' },
      { name: 'Vitamin E oil', quantity: '2 drops', purpose: 'Antioxidant, anti-aging' },
      { name: 'Tea tree oil', quantity: '1 drop', purpose: 'Antiseptic, anti-acne' },
    ],
    benefits: ['Instant soothing for sunburns & rashes', 'Deep hydration without greasiness', 'Anti-aging with collagen stimulation', 'Heals blemishes & acne scars', 'Reduces skin inflammation', 'Natural UV damage repair'],
    steps: [
      'Cut a fresh aloe vera leaf from the base of the plant.',
      'Slice it open lengthwise and scoop out the clear gel with a spoon.',
      'Blend the gel for 10 seconds to make it smooth and lump-free.',
      'Add 2 drops of vitamin E oil and 1 drop of tea tree oil.',
      'Mix gently with a clean spoon.',
      'Apply a thin, even layer on clean skin.',
      'Leave for 20-25 minutes until it dries and tightens.',
      'Rinse with cool water and pat dry gently.',
    ],
    precautions: [
      'Always do a patch test — some people are allergic to aloe vera.',
      'Use only the clear gel, not the yellow latex near the rind (it can irritate).',
      'Discard gel if it changes color or smells off.',
      'Do not apply on deep wounds or surgical incisions.',
    ],
    bestTimeToUse: 'After sun exposure or before bed',
    doshaAffinity: ['Pitta'],
    difficulty: 'Easy',
    duration: '30 mins',
    specialist: { name: 'Dr. Kavita Rao', title: 'Ayurvedic Dermatologist', image: drKavita },
    tags: ['skincare', 'hydration', 'sunburn', 'healing'],
  },
  {
    id: '7',
    category: 'hair',
    image: hairImg,
    title: 'Coconut Oil & Amla Hair Mask',
    subtitle: 'Deep nourishment for lustrous hair',
    description: 'A deeply nourishing Ayurvedic hair treatment that strengthens hair roots, prevents premature graying, and adds brilliant shine. This ancient recipe combines the moisturizing power of coconut oil with the vitamin C richness of amla.',
    ingredients: [
      { name: 'Virgin coconut oil', quantity: '3 tbsp', purpose: 'Deep conditioning, penetrates shaft' },
      { name: 'Amla powder', quantity: '1 tbsp', purpose: 'Vitamin C, prevents graying' },
      { name: 'Fresh curry leaves', quantity: '8-10 leaves', purpose: 'Prevents hair loss, adds pigment' },
      { name: 'Fenugreek seeds', quantity: '1 tsp', purpose: 'Strengthens follicles, adds volume' },
    ],
    benefits: ['Prevents hair fall by 60% with regular use', 'Delays premature graying naturally', 'Adds deep shine and softness', 'Strengthens roots and hair shafts', 'Promotes new hair growth', 'Conditions dry, damaged hair'],
    steps: [
      'Soak fenugreek seeds in 2 tbsp water for 2 hours, then grind into a paste.',
      'Heat 3 tbsp virgin coconut oil in a small pan on low flame.',
      'Add amla powder and curry leaves to the warm oil.',
      'Stir continuously on low heat for 10 minutes until the oil turns slightly greenish.',
      'Remove from heat and let it cool to a comfortable warm temperature.',
      'Mix in the fenugreek paste and stir well.',
      'Section your hair and apply the oil mixture to scalp using fingertips.',
      'Massage in circular motions for 10 minutes to stimulate blood flow.',
      'Apply remaining oil along the length of hair, focusing on ends.',
      'Cover with a warm towel or shower cap and leave for 1-2 hours (or overnight).',
      'Wash off with a mild sulfate-free shampoo. May need two washes.',
    ],
    precautions: [
      'Do not heat oil beyond warm — overheating destroys nutrients.',
      'Test temperature on your wrist before applying to scalp.',
      'If you have oily scalp, use only on hair lengths and tips.',
      'Use once a week for best results. Over-oiling can clog follicles.',
      'Ensure amla powder is pure and free from additives.',
    ],
    bestTimeToUse: 'Weekend morning or overnight before wash day',
    doshaAffinity: ['Vata', 'Pitta'],
    difficulty: 'Medium',
    duration: '1-2 hours',
    specialist: { name: 'Dr. Priya Patel', title: 'Ayurvedic Herbalist', image: drPriya },
    tags: ['haircare', 'hair-fall', 'graying', 'conditioning'],
  },
  {
    id: '8',
    category: 'hair',
    image: hairImg,
    title: 'Hibiscus Hair Rinse',
    subtitle: 'Natural conditioner & growth booster',
    description: 'Natural hair conditioner using hibiscus flowers that promotes hair growth, prevents dandruff, and adds volume. Known as "Japa" in Ayurveda, hibiscus is called the "flower of hair care" for its remarkable ability to nourish hair follicles.',
    ingredients: [
      { name: 'Red hibiscus flowers', quantity: '5-6 flowers', purpose: 'Amino acids, natural conditioner' },
      { name: 'Hibiscus leaves', quantity: '8-10 leaves', purpose: 'Natural lather, strengthening' },
      { name: 'Water', quantity: '2 cups', purpose: 'Extraction medium' },
      { name: 'Apple cider vinegar', quantity: '1 tbsp', purpose: 'pH balancer, shine enhancer' },
    ],
    benefits: ['Promotes hair growth with natural amino acids', 'Acts as a deep natural conditioner', 'Effectively fights dandruff and scalp fungus', 'Adds visible volume and bounce', 'Prevents split ends', 'Natural alternative to chemical conditioners'],
    steps: [
      'Rinse the hibiscus flowers and leaves thoroughly under running water.',
      'Tear the petals and leaves into smaller pieces to release more nutrients.',
      'Bring 2 cups of filtered water to a boil in a non-reactive pot.',
      'Add the torn hibiscus flowers and leaves to the boiling water.',
      'Reduce heat and simmer on low for 15-20 minutes until the water turns deep red.',
      'Strain the liquid into a bowl and let it cool to room temperature.',
      'Add 1 tablespoon of apple cider vinegar and mix well.',
      'After your regular shampoo wash, pour this rinse over your hair as the final step.',
      'Massage gently into the scalp for 2 minutes.',
      'Do not rinse out — let hair air dry for maximum benefit.',
    ],
    precautions: [
      'Use only red hibiscus (Hibiscus rosa-sinensis), not other varieties.',
      'May add a slight reddish tint to very light or blonde hair.',
      'Prepare fresh each time — do not store for more than 24 hours.',
      'Avoid getting into eyes as it can cause mild irritation.',
    ],
    bestTimeToUse: 'After shampoo, 1-2 times per week',
    doshaAffinity: ['Pitta', 'Kapha'],
    difficulty: 'Easy',
    duration: '25 mins',
    specialist: { name: 'Dr. Anita Desai', title: 'Digestive Health Specialist', image: drAnita },
    tags: ['haircare', 'growth', 'dandruff', 'conditioner'],
  },
  {
    id: '9',
    category: 'pain',
    image: painImg,
    title: 'Ginger & Eucalyptus Pain Balm',
    subtitle: 'Warming relief for aches & pains',
    description: 'A warming Ayurvedic remedy for joint pain, muscle soreness, and headaches using natural anti-inflammatory ingredients. This traditional pain-relief oil combines the warming properties of ginger with the penetrating action of eucalyptus.',
    ingredients: [
      { name: 'Ginger essential oil', quantity: '5 drops', purpose: 'Warming, anti-inflammatory' },
      { name: 'Eucalyptus essential oil', quantity: '5 drops', purpose: 'Penetrating, analgesic' },
      { name: 'Camphor', quantity: '1 small piece', purpose: 'Cooling-then-warming, numbing' },
      { name: 'Sesame oil', quantity: '2 tbsp', purpose: 'Deep-penetrating carrier oil' },
    ],
    benefits: ['Relieves joint pain and stiffness', 'Reduces inflammation at the source', 'Eases tension headaches and migraines', 'Improves blood circulation to affected area', 'Relaxes muscle spasms and cramps', 'Provides lasting warmth and comfort'],
    steps: [
      'Warm 2 tablespoons of cold-pressed sesame oil in a small bowl (not on direct flame).',
      'Add 5 drops each of ginger and eucalyptus essential oils to the warm sesame oil.',
      'Dissolve a small piece of camphor (pea-sized) into the oil mixture.',
      'Stir gently until camphor fully dissolves and oil is evenly mixed.',
      'Test temperature on your inner wrist — it should be comfortably warm.',
      'Apply to the affected area (joints, muscles, temples for headache).',
      'Massage using firm but gentle pressure in circular motions for 10 minutes.',
      'Cover the area with a warm cloth or towel for 15 minutes after massage.',
      'Wash off after 30 minutes with warm water, or leave overnight for severe pain.',
    ],
    precautions: [
      'Do not apply on broken skin, open wounds, or rashes.',
      'Keep away from eyes, nose, and mouth — wash hands after application.',
      'Not suitable for children under 6 years.',
      'Do not use camphor if you have epilepsy or liver conditions.',
      'Avoid during the first trimester of pregnancy.',
      'If skin irritation occurs, wash off immediately with cold water.',
    ],
    bestTimeToUse: 'Before bed or after hot shower when muscles are warm',
    doshaAffinity: ['Vata', 'Kapha'],
    difficulty: 'Easy',
    duration: '15 mins',
    specialist: { name: 'Dr. Sanjay Gupta', title: 'Sports Medicine Ayurveda', image: drSanjay },
    tags: ['pain-relief', 'joints', 'inflammation', 'headache'],
  },
  {
    id: '10',
    category: 'stress',
    image: stressImg,
    title: 'Ashwagandha Moon Milk',
    subtitle: 'Calming adaptogenic bedtime tonic',
    description: 'A calming bedtime tonic with adaptogenic ashwagandha that reduces stress, improves sleep quality, and balances cortisol levels. This "moon milk" ritual has roots in Ayurvedic practice dating back 3,000 years.',
    ingredients: [
      { name: 'Ashwagandha powder', quantity: '½ tsp', purpose: 'Adaptogen, cortisol reducer' },
      { name: 'Warm milk', quantity: '1 cup', purpose: 'Tryptophan source, calming' },
      { name: 'Nutmeg', quantity: '1 pinch', purpose: 'Natural sedative, sleep aid' },
      { name: 'Cardamom powder', quantity: '1 pinch', purpose: 'Digestive, aromatic' },
      { name: 'Raw honey', quantity: '1 tsp', purpose: 'Natural sweetener, soothing' },
    ],
    benefits: ['Reduces cortisol levels by up to 30%', 'Significantly improves sleep quality', 'Balances stress hormones naturally', 'Calms racing thoughts and anxiety', 'Strengthens nervous system over time', 'Supports healthy adrenal function'],
    steps: [
      'Pour 1 cup of whole milk (or almond/oat milk) into a small saucepan.',
      'Add ½ teaspoon of KSM-66 or regular ashwagandha powder.',
      'Add a pinch of freshly grated nutmeg and cardamom powder.',
      'Heat on low-medium flame, stirring continuously with a wooden spoon.',
      'Simmer gently for 3-4 minutes — do not let it boil vigorously.',
      'Pour into your favorite mug through a fine strainer.',
      'Let it cool for 2-3 minutes until comfortable to drink.',
      'Add 1 teaspoon of raw honey and stir well.',
      'Drink slowly and mindfully, 30-45 minutes before sleep.',
    ],
    precautions: [
      'Do not exceed ½ tsp ashwagandha — more is not better.',
      'Avoid if you have thyroid hyperthyroidism (it may increase thyroid hormones).',
      'Not recommended during pregnancy or breastfeeding.',
      'May cause drowsiness — do not drive after consumption.',
      'Discontinue if you experience stomach upset or nausea.',
      'Consult doctor if taking anti-anxiety or sleep medications.',
    ],
    bestTimeToUse: '30-45 minutes before bedtime',
    doshaAffinity: ['Vata', 'Kapha'],
    difficulty: 'Easy',
    duration: '10 mins',
    specialist: { name: 'Dr. Rajesh Sharma', title: 'Senior Ayurvedic Physician', image: drRajesh },
    tags: ['stress', 'sleep', 'anxiety', 'adaptogen'],
  },
  {
    id: '11',
    category: 'stress',
    image: stressImg,
    title: 'Brahmi & Shankhpushpi Brain Tonic',
    subtitle: 'Cognitive enhancement formula',
    description: 'An Ayurvedic brain-boosting remedy that enhances memory, reduces anxiety, and improves cognitive function naturally. Both Brahmi and Shankhpushpi are classified as "Medhya Rasayana" — herbs that rejuvenate the mind and intellect.',
    ingredients: [
      { name: 'Brahmi powder', quantity: '½ tsp', purpose: 'Neuroprotective, memory enhancer' },
      { name: 'Shankhpushpi powder', quantity: '½ tsp', purpose: 'Cognitive enhancer, anxiolytic' },
      { name: 'Warm water', quantity: '1 cup', purpose: 'Extraction medium' },
      { name: 'Honey', quantity: '1 tsp', purpose: 'Carrier, taste enhancer' },
    ],
    benefits: ['Enhances memory retention and recall', 'Reduces anxiety and mental fatigue', 'Improves concentration and focus', 'Neuroprotective against cognitive decline', 'Balances neurotransmitter levels', 'Supports healthy brain aging'],
    steps: [
      'Boil 1 cup of filtered water and let it cool to lukewarm.',
      'Add ½ teaspoon each of organic brahmi and shankhpushpi powder.',
      'Stir vigorously for 30 seconds to ensure even mixing.',
      'Let the mixture steep for 3-5 minutes.',
      'Add 1 teaspoon of raw honey and stir well.',
      'Drink the entire mixture including any sediment.',
    ],
    precautions: [
      'May cause slight drowsiness in some individuals.',
      'Start with ¼ tsp each for the first week to assess tolerance.',
      'Not recommended for children under 5 years without medical guidance.',
      'Avoid combining with sedative medications.',
      'Take a 1-week break every month for best results.',
    ],
    bestTimeToUse: 'Morning for focus, or evening for calming',
    doshaAffinity: ['Pitta', 'Vata'],
    difficulty: 'Easy',
    duration: '5 mins',
    specialist: { name: 'Dr. Vikram Chauhan', title: 'Panchakarma Expert', image: drVikram },
    tags: ['brain', 'memory', 'anxiety', 'focus'],
  },
  {
    id: '12',
    category: 'pain',
    image: painImg,
    title: 'Ajwain Steam Inhalation',
    subtitle: 'Instant sinus & congestion relief',
    description: 'Effective remedy for sinus congestion, cold, and headache using carom seeds steam therapy. Ajwain (carom seeds) contains thymol, a powerful antiseptic compound that opens airways and kills respiratory pathogens on contact.',
    ingredients: [
      { name: 'Ajwain seeds', quantity: '1 tbsp', purpose: 'Thymol-rich, antiseptic' },
      { name: 'Water', quantity: '3 cups', purpose: 'Steam generation' },
      { name: 'Eucalyptus oil', quantity: '2 drops', purpose: 'Decongestant, refreshing' },
    ],
    benefits: ['Clears blocked sinuses within minutes', 'Relieves sinus headache and pressure', 'Opens restricted airways', 'Fights cold and flu symptoms', 'Natural expectorant for chest congestion', 'Soothes irritated nasal passages'],
    steps: [
      'Bring 3 cups of water to a rolling boil in a wide, stable pot.',
      'Add 1 tablespoon of ajwain seeds to the boiling water.',
      'Let it boil for 2 minutes to release the thymol compounds.',
      'Remove from heat and place the pot on a stable surface (table).',
      'Add 2 drops of eucalyptus oil to the hot water.',
      'Sit comfortably and lean over the pot at a safe distance (12 inches).',
      'Drape a large towel over your head and the pot to create a tent.',
      'Breathe in deeply through your nose and out through your mouth.',
      'Continue for 10-15 minutes, taking breaks if needed.',
      'After the session, gently blow your nose to clear loosened mucus.',
    ],
    precautions: [
      'Keep pot stable to avoid spilling hot water — burns risk.',
      'Maintain at least 12 inches distance from the hot water surface.',
      'Not suitable for children under 8 — supervision required for ages 8-12.',
      'Avoid if you have asthma — steam may trigger bronchospasm.',
      'Do not use more than twice daily.',
      'If you feel dizzy or faint during inhalation, stop immediately.',
    ],
    bestTimeToUse: 'Before bed and morning when congested',
    doshaAffinity: ['Kapha', 'Vata'],
    difficulty: 'Easy',
    duration: '20 mins',
    specialist: { name: 'Dr. Sanjay Gupta', title: 'Sports Medicine Ayurveda', image: drSanjay },
    tags: ['sinus', 'congestion', 'cold', 'headache'],
  },
];
